default_install_hook_types: [pre-commit, pre-push]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.0.292
      hooks:
          - id: ruff
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.942
      hooks:
          - id: mypy
            additional_dependencies: ['types-requests']
    - repo: https://github.com/pdm-project/pdm
      rev: 2.8.1
      hooks:
          - id: pdm-export
            stages: [pre-push]
            args: ["-o", "requirements.txt", "--prod"]
          - id: pdm-lock-check
            stages: [pre-push]
